{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "notification-system.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification-system.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq .service "api" }}
                name: {{ include "notification-system.fullname" $ }}-api
                port:
                  number: {{ $.Values.api.service.port }}
                {{- else if eq .service "worker" }}
                name: {{ include "notification-system.fullname" $ }}-worker
                port:
                  number: {{ $.Values.worker.service.port }}
                {{- else }}
                name: {{ include "notification-system.fullname" $ }}-ui
                port:
                  number: {{ $.Values.ui.service.port }}
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
